apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devdan-pod-reader
  namespace: prod
subjects:
- kind: User
  name: devdan
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
